# Image upload
leapt_froala_editor_upload_image:
    path: /upload_image
    controller: Leapt\FroalaEditorBundle\Controller\MediaController::uploadImage

leapt_froala_editor_delete_image:
    path: /delete_image
    controller: Leapt\FroalaEditorBundle\Controller\MediaController::deleteImage

leapt_froala_editor_load_images:
    path: /load_images
    controller: Leapt\FroalaEditorBundle\Controller\MediaController::loadImages

# File upload
leapt_froala_editor_upload_file:
    path: /upload_file
    controller: Leapt\FroalaEditorBundle\Controller\MediaController::uploadFile

# Video upload
leapt_froala_editor_upload_video:
    path: /upload_video
    controller: Leapt\FroalaEditorBundle\Controller\MediaController::uploadVideo
