services:
    # Command.
    Leapt\FroalaEditorBundle\Command\InstallCommand:
        tags:
            - { name: "console.command", command: "froala:install" }

    # Controller.
    Leapt\FroalaEditorBundle\Controller\MediaController:
        arguments: [ "@leapt_froala_editor.media_manager", "@kernel" ]
        public: true

    # Form type.
    leapt_froala_editor.form.type:
        class: "Leapt\\FroalaEditorBundle\\Form\\Type\\FroalaEditorType"
        arguments: [ "@parameter_bag", "@leapt_froala_editor.option_manager", "@leapt_froala_editor.plugin_provider" ]
        tags:
            - { name: "form.type" }

    # Option manager.
    leapt_froala_editor.option_manager:
        class: "Leapt\\FroalaEditorBundle\\Service\\OptionManager"
        arguments: [ "@router" ]

    # Plugin provider.
    leapt_froala_editor.plugin_provider:
        class: "Leapt\\FroalaEditorBundle\\Service\\PluginProvider"

    # Media manager.
    leapt_froala_editor.media_manager:
        class: "Leapt\\FroalaEditorBundle\\Service\\MediaManager"
        public: true

    # Twig extension.
    leapt_froala_editor.froala_extension:
        class: "Leapt\\FroalaEditorBundle\\Twig\\FroalaExtension"
        arguments: [ "@parameter_bag", "@assets.packages" ]
        tags:
            - { name: twig.extension }
